# -*- coding: utf-8 -*-
"""panorama_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_xMBk5aScNi_73GH0L5hXmfVQczersh
"""

#Import packages
import cv2
import numpy as np
import imutils
from google.colab.patches import cv2_imshow

def extract_frames(video_path, skip_frames=10):
    """Extracts frames from a video at regular intervals."""
    cap = cv2.VideoCapture(video_path)
    frames = []
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break  # End of video
        if frame_count % skip_frames == 0:
            frames.append(frame)
        frame_count += 1

    cap.release()
    return frames

def stitch_images(images):
    """Stitches images to create a panorama using feature matching."""
    stitcher = cv2.Stitcher_create()
    (status, panorama) = stitcher.stitch(images)

    if status != cv2.Stitcher_OK:
        print("Error: Image stitching failed!")
        return None

    return panorama

def main(video_path, output_path, skip_frames = 10):
    """Extracts frames, stitches them, and saves the panorama."""
    print("Extracting frames from video...")
    frames = extract_frames(video_path, skip_frames)

    if len(frames) < 2:
        print("Not enough frames for stitching!")
        return

    print("Stitching images to create a panorama...")
    panorama = stitch_images(frames)

    if panorama is not None:
        cv2.imwrite(output_path, panorama)
        print(f"Panorama saved as {output_path}")
        cv2_imshow(imutils.resize(panorama, width=1000))
    else:
        print("Failed to generate panorama.")

# Example usage
if __name__ == "__main__":
    video_file = "/content/drive/MyDrive/panorama_gen/panorama_v3.mp4"  # Change to your video file
    output_file ="/content/drive/MyDrive/panorama_gen/panorama_v3.jpg" # change to your output file
    skip_frames = 10 # define
    main(video_file,output_file)